zap:
  level: 'info'
  format: 'console'
  prefix: '[GIN-DEMO]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

mysql:
  path: ''
  config: ''
  db-name: ''
  username: ''
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: ""

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8080